In [3]:
class Account:
    def __init__(self, number, rate=0.01):
        self.number = number
        self.balance = 0
        self.rate = rate
        
        
    def deposit(self, amount):
        self.balance += amount
        
        
    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            
            
    def obtain_interest(self):
        self.balance += self.balance * self.rate
        
        
    def transfer(self, other, amount):
        if amount <= self.balance:
            self.balance -= amount
            other.balance += amount
            print('이체 성공. 잔액={}'.format(self.balance))
        else:
            print('잔고가 부족합니다. 잔액={}'.format(self.balance))

In [4]:
acc1 = Account(1001)
acc2 = Account(1002)
acc3 = Account(1003)

acc1.deposit(500)
acc2.deposit(1000)

acc1.transfer(acc2, 1000)
acc2.transfer(acc1, 1000)

잔고가 부족합니다. 잔액=500
이체 성공. 잔액=0


In [9]:
class Account:
    def __init__(self, number, rate=0.01):
        self.number = number
        self.balance = 0
        self.rate = rate
        
        
    def deposit(self, amount):
        self.balance += amount
        
        
    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            
            
    def obtain_interest(self):
        self.balance += self.balance * self.rate
        
        
    def transfer(self, other, amount):
        if amount <= self.balance:
            self.balance -= amount
            other.balance += amount
            print('이체 성공. 잔액={}'.format(self.balance))
        else:
            print('잔고가 부족합니다. 잔액={}'.format(self.balance))
            
    def __iadd__(self, amount):
        self.deposit(amount)
        return self
    
    def __isub__(self, amount):
        self.withdraw(amount)
        return self
    
acc = Account(1000)

In [10]:
print(acc.balance)

0


In [11]:
acc += 1000

In [12]:
print(acc.balance)

1000


In [ ]:
# set을 모방하는 클래스 Set을 구현해라

In [17]:
iter([1,2,3])

In [22]:
class Reverse:
    def __init__(self, data):
        self.data = data
        self.index = len(data)
        
    def __iter__(self):
        return self
        
    def __next__(self):
        if self.index == 0:
            raise StopIteration
        self.index -= 1
        return self.data[self.index]

In [45]:
a = Reverse([1,2,3,4,5,6])

In [46]:
# iterator는 for문이 연속적으로 동작하지 않는다. 파일 읽기와 비슷함.

for i in a:
    print(i)

6
5
4
3
2
1


In [54]:
# generator는 함수 형태로 작성함. yield 사용

def reverse(input_string):
    for i in range(len(input_string) - 1, -1, -1):
        yield input_string[i]

In [55]:
for i in reverse('hello'):
    print(i)

o
l
l
e
h


In [ ]:
# generator comprehension ... ()로 감싸서 쓰면 generator 객체가 만들어짐
# 함수 = 1급 객체 (first-class object)

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6]])

In [4]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [5]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

2
(2, 3)
6
int64
8


In [6]:
a = np.array([2,3,4])

In [7]:
a

array([2, 3, 4])

In [8]:
a.dtype

dtype('int64')

In [9]:
b = np.array([1.2, 3.5, 5.1])

In [10]:
b.dtype

dtype('float64')

In [11]:
a = np.array([1,2,3,4])

In [12]:
c = np.array([ [1,2], [3, 4] ], dtype=complex)

In [13]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [14]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
# np.arange는 잘 쓰지 않는다
# linspace를 써보자.

In [15]:
a = np.arange(6)

In [16]:
a

array([0, 1, 2, 3, 4, 5])

In [17]:
b = np.arange(12).reshape(4,3)

In [18]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
c = np.arange(24).reshape(2,3,4)

In [20]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [22]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [23]:
x = np.arange(10)

In [24]:
x[2]

2

In [25]:
x[-2]

8

In [26]:
x.shape = (2,5)

In [27]:
x[1,3]

8

In [28]:
x[1,-1]

9

In [29]:
x[0]

array([0, 1, 2, 3, 4])

In [30]:
x[0][2]

2

In [31]:
x[0,2]

2

In [ ]:
# x[0][2] = x[0, 2]

In [32]:
x = np.arange(10)

In [33]:
x.shape = (2,5)

In [34]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
x[1,-1]

9

In [36]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(a[[0,1,2,0], [0,2,0,1]])

[1 6 7 2]


In [38]:
b = np.array([0,2,0,1])
print(a[b,b])

[1 9 1 5]


In [39]:
x = np.arange(10)
x[2:5]

array([2, 3, 4])

In [40]:
x[:-7]

array([0, 1, 2])

In [41]:
x[1:7:2]

array([1, 3, 5])

In [42]:
y = np.arange(35).reshape(5, 7)

In [43]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [44]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [45]:
a = np.array([[1,2], [3,4], [5,6]])

In [46]:
bool_idx = (a > 2)

In [47]:
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [48]:
print(a[bool_idx])

[3 4 5 6]


In [49]:
print(a[a > 2])

[3 4 5 6]


In [50]:
a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
b = a[:2]
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# a와 b가 주소는 달라도 값은 동일하게 바뀐다 (shallow copy)

In [55]:
b = 10 * np.random.random((3,4))
print(b)
a = np.floor(b)
print(a)

[[5.42440599 8.46240401 7.56716375 0.39269022]
 [1.57796078 5.39462216 0.41943397 3.17231479]
 [8.09092321 1.65636061 8.65471875 5.6547882 ]]
[[5. 8. 7. 0.]
 [1. 5. 0. 3.]
 [8. 1. 8. 5.]]


In [ ]:
# shift + tap 눌러서 IN PLACE 적혀있으면 반환값 없이 결과 수정

In [67]:
# 실습 문제1

a = np.zeros([5,5])
b = np.ones([3,3])

a[1:4, 1:4] = b
print(a)
print()

c = np.ones([5,5])
d = np.zeros([3,3])
c[1:4, 1:4] = d
print(c)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [87]:
# 실습 문제2

e = np.zeros([8,8])

e[::2,1::2] = 1
e[1::2,::2] = 1

print(e)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [88]:
# 실습 문제3

f = np.array([180, 72, 172, 66, 162, 60, 167, 53, 176, 80, 155, 60, 177, 77, 130, 40])

In [92]:
f.shape

(16,)

In [91]:
f.reshape(2,4,2)

array([[[180,  72],
        [172,  66],
        [162,  60],
        [167,  53]],

       [[176,  80],
        [155,  60],
        [177,  77],
        [130,  40]]])

In [95]:
# 실습 문제4

def linear_system_solver(ndarr, v):
    result = np.linalg.inv(ndarr) @ v
    return result

In [96]:
a = np.array([[1, 1],
              [2, 1]])

b = np.array([15,25])

linear_system_solver(a,b)

array([10.,  5.])

In [ ]:
# 실습 문제5


In [1]:
sList = [[201801, 84, 73], [201802, 92, 89], [201803, 57, 62], [201804, 58, 68]]

In [2]:
sList

[[201801, 84, 73], [201802, 92, 89], [201803, 57, 62], [201804, 58, 68]]

In [3]:
sList[1]

[201802, 92, 89]

In [4]:
sList[1][2]

89

In [1]:
import arth

In [2]:
arth.add(100, 200)

300